from enum import Enum


class Gui_Element(Enum):
    NONE = 0
    END_LEFT = 1
    END_RIGHT = 2
    TOP_LEFT = 3
    BOTTOM_LEFT = 5
    BUTTON = 6
    BUTTON_FULL_CIRCLE = 7
    BUTTON_SEMI_LEFT = 8
    BUTTON_SEMI_RIGHT = 9
    BUTTON_NOTIFICATION_FULL_CIRCLE = 10
    BUTTON_FULL_CIRCLE_TEXT = 11
