from enum import Enum


class Gui_Element(Enum):
    NONE = 0
    END_LEFT = 1
    END_RIGHT = 2
    TOP_LEFT = 3
    TOP_LEFT_SHORT = 4
    BOTTOM_LEFT = 5
    BOTTOM_LEFT_SHORT = 6
    BUTTON = 7
    BUTTON_FULL_CIRCLE = 8
    BUTTON_SEMI_LEFT = 9
    BUTTON_SEMI_RIGHT = 10
    BUTTON_NOTIFICATION_FULL_CIRCLE = 11
    BUTTON_FULL_CIRCLE_TEXT = 12
